create table
    users (
        user_id INT,
        username VARCHAR(50),
        email VARCHAR(50),
        birthdate DATE,
        gender VARCHAR(10),
        phone_number VARCHAR(10)
    ),
    (
        1,
        'kdebeauchamp0',
        'vgaskamp0@redcross.org',
        '4/18/1965',
        'non-binary',
        'male'
    ),
    (
        2,
        'npeachman1',
        'lmichelle1@trellian.com',
        '5/30/1969',
        'female',
        'female'
    ),
    (
        3,
        'cbitcheno2',
        'adedei2@booking.com',
        '8/3/1970',
        'non-binary',
        'female'
    ),
    (
        4,
        'bskones3',
        'mcrann3@usatoday.com',
        '6/14/1984',
        'female',
        'female'
    ),
    (
        5,
        'ahartwright4',
        'nruscoe4@theguardian.com',
        '6/1/1968',
        'male',
        'male'
    ),
    (
        6,
        'wisherwood5',
        'glynskey5@ning.com',
        '8/25/1993',
        'female',
        'non-binary'
    ),
    (
        7,
        'rbloore6',
        'cdows6@telegraph.co.uk',
        '1/30/1971',
        'female',
        'non-binary'
    ),
    (
        8,
        'ivenney7',
        'ililleyman7@tamu.edu',
        '2/21/1969',
        'male',
        'non-binary'
    ),
    (
        9,
        'mabisetti8',
        'agrube8@nhs.uk',
        '9/8/1974',
        'female',
        'non-binary'
    ),
    (
        10,
        'pboon9',
        'ahevey9@issuu.com',
        '9/6/1957',
        'male',
        'non-binary'
    ),
    (
        11,
        'sdeleona',
        'swalesbya@wordpress.com',
        '8/15/1979',
        'male',
        'male'
    ),
    (
        12,
        'bwindebankb',
        'tkneeshawb@last.fm',
        '8/30/1991',
        'female',
        'female'
    ),
    (
        13,
        'kellingfordc',
        'tjarrattc@elegantthemes.com',
        '1/6/1951',
        'female',
        'male'
    ),
    (
        14,
        'vnanid',
        'ejuliend@yellowpages.com',
        '6/6/1956',
        'male',
        'male'
    ),
    (
        15,
        'mleatheme',
        'lwynnee@cornell.edu',
        '11/5/1959',
        'male',
        'female'
    ),
    (
        16,
        'cmcboylef',
        'gguineryf@webmd.com',
        '2/1/1967',
        'non-binary',
        'male'
    ),
    (
        17,
        'cbrinkmang',
        'osedgwickg@bandcamp.com',
        '6/13/1961',
        'female',
        'female'
    ),
    (
        18,
        'marborh',
        'dbuzzingh@odnoklassniki.ru',
        '10/8/1962',
        'male',
        'female'
    ),
    (
        19,
        'mheffroni',
        'kvanderkruisi@independent.co.uk',
        '2/8/1984',
        'female',
        'male'
    ),
    (
        20,
        'hbrunettij',
        'asitwellj@dagondesign.com',
        '3/16/1994',
        'male',
        'female'
    ),
    (
        21,
        'ahavek',
        'wesbyk@foxnews.com',
        '4/21/1950',
        'non-binary',
        'non-binary'
    ),
    (
        22,
        'cmilloml',
        'rhyndmanl@loc.gov',
        '1/23/1951',
        'non-binary',
        'non-binary'
    ),
    (
        23,
        'dkiffem',
        'nghiraldim@booking.com',
        '1/10/1969',
        'non-binary',
        'male'
    ),
    (
        24,
        'dcaldeiron',
        'rmundeen@businessweek.com',
        '6/6/1997',
        'male',
        'female'
    ),
    (
        25,
        'dbooio',
        'etolleto@amazon.co.uk',
        '12/15/1994',
        'non-binary',
        'male'
    ),
    (
        26,
        'dsmealp',
        'eklusp@shinystat.com',
        '1/4/1955',
        'male',
        'female'
    ),
    (
        27,
        'jskethq',
        'dphilotq@nature.com',
        '11/24/1972',
        'non-binary',
        'male'
    ),
    (
        28,
        'bgoadsbyr',
        'gblestr@bbc.co.uk',
        '6/26/1950',
        'male',
        'non-binary'
    ),
    (
        29,
        'arablans',
        'osmorfits@plala.or.jp',
        '4/23/1978',
        'non-binary',
        'female'
    ),
    (
        30,
        'lcastillot',
        'hwoostert@ox.ac.uk',
        '1/27/1994',
        'female',
        'male'
    );